use sha2::{Digest, Sha256};
use tracing::warn;

use crate::{
    database::{
        device_risk,
        device_state::{self, DeviceObservation, DeviceTelemetryKind, TimedDimension},
        ingest_auth, ingest_nonce,
        telemetry::TelemetryScope,
    },
    domain::telemetry::{
        BatchReceipt, ErrorInput, EventInput, LogInput, MAX_BATCH_ITEMS, MetricInput, RejectedItem,
        ValidateTelemetry,
    },
    error::AppError,
    ingest_signature,
    state::InstalledState,
};

use super::{
    ingest_abuse::{self, RiskTier},
    ingest_bootstrap,
};

#[derive(Clone, Copy, Debug)]
pub struct IngestTokenContext<'a> {
    pub client_ip: &'a str,
    pub user_agent: &'a str,
    pub raw_key: Option<&'a str>,
}

#[derive(Clone, Copy, Debug)]
pub struct IngestRequestContext<'a> {
    pub client_ip: &'a str,
    pub user_agent: &'a str,
    pub credential: Option<&'a str>,
    pub signature: Option<&'a str>,
    pub timestamp: Option<&'a str>,
    pub nonce: Option<&'a str>,
    pub method: &'a str,
    pub path: &'a str,
}

#[derive(Clone, Debug)]
pub struct IngestScope {
    pub application_id: String,
    pub environment_id: String,
    source_ip: String,
    device_id: String,
    risk_tier: RiskTier,
}

impl IngestScope {
    fn storage_scope(&self) -> TelemetryScope {
        TelemetryScope {
            application_id: self.application_id.clone(),
            environment_id: self.environment_id.clone(),
        }
    }

    pub(crate) fn signed_device_id(&self) -> &str {
        &self.device_id
    }
}

#[derive(Debug, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct IngestTokenRequest {
    /// Stable pseudonymous identifier generated by the client for the current device.
    /// Historical activity/session/version/OS state is derived from telemetry by the platform.
    pub device_id: String,
}

#[derive(Debug, serde::Serialize)]
#[serde(rename_all = "camelCase")]
pub struct IngestTokenResponse {
    pub token: String,
    pub token_type: &'static str,
    pub expires_in: i64,
    pub expires_at: i64,
    pub signing_key: String,
    pub signature_version: &'static str,
    pub scopes: Vec<String>,
}

pub fn has_permission(scopes: &[String], required_perm: &str) -> bool {
    scopes.iter().any(|scope| {
        scope == "*"
            || scope == "ingest"
            || scope == "telemetry.ingest"
            || scope == required_perm
            || (required_perm == "telemetry.events"
                && (scope == "events" || scope == "ingest.events"))
            || (required_perm == "telemetry.metrics"
                && (scope == "metrics" || scope == "ingest.metrics"))
            || (required_perm == "telemetry.logs"
                && (scope == "logs" || scope == "ingest.logs"))
            || (required_perm == "telemetry.errors"
                && (scope == "errors" || scope == "ingest.errors"))
    })
}

pub fn match_user_agent(rule: &str, user_agent: &str) -> bool {
    let rule = rule.trim();
    if rule.is_empty() || rule == "*" {
        return true;
    }
    if user_agent.is_empty() {
        return false;
    }
    for part in rule.split(',') {
        let pattern = part.trim();
        if pattern.is_empty() {
            continue;
        }
        if let Some(prefix) = pattern.strip_suffix('*') {
            if user_agent.starts_with(prefix) {
                return true;
            }
        } else if user_agent == pattern || user_agent.contains(pattern) {
            return true;
        }
    }
    false
}

/// Exchange a long-lived bootstrap API key for a short-lived device-bound ingest token.
pub async fn issue_token(
    installed: &InstalledState,
    request: IngestTokenContext<'_>,
    body: IngestTokenRequest,
) -> Result<IngestTokenResponse, AppError> {
    let user_agent = validate_user_agent(request.user_agent)?;
    let pepper = installed.auth_security.pepper();

    if !ingest_bootstrap::charge_ip_token(&installed.database, pepper, request.client_ip).await? {
        return Err(AppError::TooManyRequests);
    }

    let device_id = validate_device_id(&body.device_id)?.to_owned();
    let raw_key = request.raw_key.ok_or(AppError::Unauthorized)?;
    let hash = hex::encode(Sha256::digest(raw_key.as_bytes()));
    let context = ingest_auth::api_key_context(
        &installed.database,
        &hash,
        chrono::Utc::now().timestamp_millis(),
    )
    .await?
    .ok_or(AppError::Unauthorized)?;

    if !ingest_bootstrap::check_device_enrollment(
        &installed.database,
        pepper,
        request.client_ip,
        &context.application_id,
        &device_id,
    )
    .await?
    {
        return Err(AppError::TooManyRequests);
    }

    let salt = format!("{}:{}", context.application_id, context.environment_id);
    let device_hash = anonymous_hash(&device_id, &salt);
    let risk_score = device_risk::risk_score_for_device(
        &installed.database,
        &context.application_id,
        &context.environment_id,
        &device_hash,
    )
    .await?
    .unwrap_or(0);
    let policy = ingest_abuse::policy_for_score(risk_score);
    if !charge_device_token_budget(
        installed,
        &context.application_id,
        &device_id,
        policy.token_cost_multiplier,
    )
    .await?
    {
        return Err(AppError::TooManyRequests);
    }

    let client_binding = installed
        .auth_security
        .ingest
        .client_binding(user_agent, pepper);
    let claim_scopes = ingest_abuse::claims_scopes(&context.scopes, policy.tier);
    let (token, signing_key, expires_at) = installed.auth_security.ingest.issue_ingest_token(
        &context.application_id,
        &context.environment_id,
        &device_id,
        &client_binding,
        &claim_scopes,
        policy.token_ttl_seconds,
        pepper,
    )?;

    Ok(IngestTokenResponse {
        token,
        token_type: "Bearer",
        expires_in: policy.token_ttl_seconds,
        expires_at,
        signing_key,
        signature_version: ingest_signature::SIGNATURE_VERSION,
        scopes: context.scopes,
    })
}

pub async fn scope_from_context_with_permission(
    installed: &InstalledState,
    request: IngestRequestContext<'_>,
    required_perm: &str,
    raw_body: &[u8],
) -> Result<IngestScope, AppError> {
    let user_agent = validate_user_agent(request.user_agent)?;

    if !installed
        .auth_security
        .ingest
        .check_ip_ingest_rate(request.client_ip)
        .await
        || !installed
            .auth_security
            .ingest
            .check_ip_ingest_bytes(request.client_ip, raw_body.len())
            .await
    {
        return Err(AppError::TooManyRequests);
    }

    let auth_header = request.credential.ok_or(AppError::Unauthorized)?;
    if !auth_header.starts_with("sndt_") {
        return Err(AppError::IngestTokenRequired);
    }
    signed_scope(installed, request, required_perm, raw_body, auth_header, user_agent).await
}

async fn signed_scope(
    installed: &InstalledState,
    request: IngestRequestContext<'_>,
    required_perm: &str,
    raw_body: &[u8],
    token: &str,
    user_agent: &str,
) -> Result<IngestScope, AppError> {
    let claims = installed
        .auth_security
        .ingest
        .verify_ingest_token(token, installed.auth_security.pepper())
        .ok_or(AppError::Unauthorized)?;
    let policy = ingest_abuse::policy_for_claims(&claims.scopes);

    let expected_binding = installed
        .auth_security
        .ingest
        .client_binding(user_agent, installed.auth_security.pepper());
    if claims.client_binding != expected_binding || !has_permission(&claims.scopes, required_perm) {
        return Err(AppError::Forbidden);
    }

    let signature = request.signature.ok_or(AppError::Forbidden)?;
    let timestamp = request
        .timestamp
        .ok_or(AppError::Forbidden)?
        .parse::<i64>()
        .map_err(|_| AppError::Validation("invalid x-sonde-timestamp".into()))?;
    let nonce = request.nonce.ok_or(AppError::Forbidden)?;
    if nonce.len() < 8
        || nonce.len() > 128
        || nonce
            .chars()
            .any(|character| character.is_control() || character.is_whitespace())
    {
        return Err(AppError::Validation(
            "x-sonde-nonce must be 8..128 visible non-whitespace bytes".into(),
        ));
    }

    let signing_key = installed
        .auth_security
        .ingest
        .signing_key_for_claims(&claims, installed.auth_security.pepper());
    ingest_signature::verify(
        &signing_key,
        timestamp,
        nonce,
        request.method,
        request.path,
        raw_body,
        signature,
    )?;

    if !ingest_nonce::record_once(
        &installed.database,
        &claims.token_id,
        nonce,
        claims.expires_at,
    )
    .await?
    {
        let device_hash = anonymous_hash(
            &claims.device_id,
            &format!("{}:{}", claims.application_id, claims.environment_id),
        );
        let now = chrono::Utc::now().timestamp_millis();
        if let Err(error) = device_risk::record_replay_detected(
            &installed.database,
            &claims.application_id,
            &claims.environment_id,
            &device_hash,
            now,
        )
        .await
        {
            warn!(
                error = %error,
                application_id = %claims.application_id,
                environment_id = %claims.environment_id,
                "failed to record verified ingest replay risk signal"
            );
        }
        warn!(
            application_id = %claims.application_id,
            environment_id = %claims.environment_id,
            source_ip = %request.client_ip,
            device_hash = %device_hash,
            "replayed signed ingest request rejected"
        );
        return Err(AppError::Forbidden);
    }

    if !charge_device_request_budget(
        installed,
        &claims.application_id,
        &claims.device_id,
        policy.request_cost_multiplier,
    )
    .await
        || !installed
            .auth_security
            .ingest
            .check_device_ingest_bytes(
                &claims.application_id,
                &claims.device_id,
                ingest_abuse::scaled_cost(raw_body.len(), policy.byte_cost_multiplier),
            )
            .await
    {
        return Err(AppError::TooManyRequests);
    }

    Ok(IngestScope {
        application_id: claims.application_id,
        environment_id: claims.environment_id,
        source_ip: request.client_ip.to_owned(),
        device_id: claims.device_id,
        risk_tier: policy.tier,
    })
}

pub async fn events(
    installed: &InstalledState,
    scope: &IngestScope,
    mut items: Vec<EventInput>,
) -> Result<BatchReceipt, AppError> {
    ensure_batch_size(items.len())?;
    charge_item_budget(installed, scope, items.len()).await?;
    let (accepted, rejected) = validate_with(&mut items, |item| normalize_live_event(scope, item));
    let mut valid = select_valid(items, &rejected);
    let observation = event_observation(&valid);
    let key_salt = format!("{}:{}", scope.application_id, scope.environment_id);
    for item in &mut valid {
        item.anonymous_id = item
            .anonymous_id
            .take()
            .map(|id| anonymous_hash(&id, &key_salt));
    }
    let storage_scope = scope.storage_scope();
    installed
        .ingest_writer
        .write_events(&storage_scope, valid)
        .await?;
    observe_signed_device(installed, scope, &storage_scope, observation).await;
    Ok(BatchReceipt { accepted, rejected })
}

pub async fn metrics(
    installed: &InstalledState,
    scope: &IngestScope,
    mut items: Vec<MetricInput>,
) -> Result<BatchReceipt, AppError> {
    ensure_batch_size(items.len())?;
    charge_item_budget(installed, scope, items.len()).await?;
    let (accepted, rejected) = validate_with(&mut items, |item| {
        item.timestamp = None;
        Ok(())
    });
    let valid = select_valid(items, &rejected);
    let observation = simple_observation(DeviceTelemetryKind::Metric, valid.len());
    let storage_scope = scope.storage_scope();
    installed
        .ingest_writer
        .write_metrics(&storage_scope, valid)
        .await?;
    observe_signed_device(installed, scope, &storage_scope, observation).await;
    Ok(BatchReceipt { accepted, rejected })
}

pub async fn logs(
    installed: &InstalledState,
    scope: &IngestScope,
    mut items: Vec<LogInput>,
) -> Result<BatchReceipt, AppError> {
    ensure_batch_size(items.len())?;
    charge_item_budget(installed, scope, items.len()).await?;
    let (accepted, rejected) = validate_with(&mut items, |item| {
        item.timestamp = None;
        Ok(())
    });
    let valid = select_valid(items, &rejected);
    let observation = simple_observation(DeviceTelemetryKind::Log, valid.len());
    let storage_scope = scope.storage_scope();
    installed
        .ingest_writer
        .write_logs(&storage_scope, valid)
        .await?;
    observe_signed_device(installed, scope, &storage_scope, observation).await;
    Ok(BatchReceipt { accepted, rejected })
}

pub async fn errors(
    installed: &InstalledState,
    scope: &IngestScope,
    mut items: Vec<ErrorInput>,
) -> Result<BatchReceipt, AppError> {
    ensure_batch_size(items.len())?;
    charge_item_budget(installed, scope, items.len()).await?;
    let (accepted, rejected) = validate_with(&mut items, |item| normalize_live_error(scope, item));
    let valid = select_valid(items, &rejected);
    let observation = error_observation(&valid);
    let storage_scope = scope.storage_scope();
    installed
        .ingest_writer
        .write_errors(&storage_scope, valid)
        .await?;
    observe_signed_device(installed, scope, &storage_scope, observation).await;
    Ok(BatchReceipt { accepted, rejected })
}

async fn observe_signed_device(
    installed: &InstalledState,
    scope: &IngestScope,
    storage_scope: &TelemetryScope,
    observation: Option<DeviceObservation>,
) {
    let Some(observation) = observation else {
        return;
    };
    let salt = format!("{}:{}", scope.application_id, scope.environment_id);
    let device_hash = anonymous_hash(scope.signed_device_id(), &salt);
    if let Err(error) = device_state::observe(
        &installed.database,
        storage_scope,
        &device_hash,
        &observation,
    )
    .await
    {
        warn!(
            error = %error,
            application_id = %scope.application_id,
            environment_id = %scope.environment_id,
            "failed to update derived device profile after telemetry ingest"
        );
    }
}

fn event_observation(items: &[EventInput]) -> Option<DeviceObservation> {
    if items.is_empty() {
        return None;
    }
    let received_at = chrono::Utc::now().timestamp_millis();
    let mut app_version = None;
    let mut launcher_version = None;
    let mut os = None;
    for item in items {
        update_current_dimension(&mut app_version, item.app_version.as_deref(), received_at);
        update_current_dimension(
            &mut launcher_version,
            item.launcher_version.as_deref(),
            received_at,
        );
        update_current_dimension(&mut os, item.os.as_deref(), received_at);
    }
    Some(DeviceObservation {
        kind: DeviceTelemetryKind::Event,
        received_at,
        telemetry_at: received_at,
        item_count: items.len(),
        session_id: None,
        app_version,
        launcher_version,
        os,
    })
}

fn error_observation(items: &[ErrorInput]) -> Option<DeviceObservation> {
    if items.is_empty() {
        return None;
    }
    let received_at = chrono::Utc::now().timestamp_millis();
    let mut app_version = None;
    let mut launcher_version = None;
    let mut os = None;
    for item in items {
        update_current_dimension(&mut app_version, item.app_version.as_deref(), received_at);
        update_current_dimension(
            &mut launcher_version,
            item.launcher_version.as_deref(),
            received_at,
        );
        update_current_dimension(&mut os, item.os.as_deref(), received_at);
    }
    Some(DeviceObservation {
        kind: DeviceTelemetryKind::Error,
        received_at,
        telemetry_at: received_at,
        item_count: items.len(),
        session_id: None,
        app_version,
        launcher_version,
        os,
    })
}

fn simple_observation(kind: DeviceTelemetryKind, item_count: usize) -> Option<DeviceObservation> {
    if item_count == 0 {
        return None;
    }
    let received_at = chrono::Utc::now().timestamp_millis();
    Some(DeviceObservation {
        kind,
        received_at,
        telemetry_at: received_at,
        item_count,
        session_id: None,
        app_version: None,
        launcher_version: None,
        os: None,
    })
}

fn update_current_dimension(
    target: &mut Option<TimedDimension>,
    value: Option<&str>,
    received_at: i64,
) {
    let Some(value) = value else {
        return;
    };
    *target = Some(TimedDimension {
        value: value.to_owned(),
        timestamp: received_at,
    });
}

async fn charge_item_budget(
    installed: &InstalledState,
    scope: &IngestScope,
    item_count: usize,
) -> Result<(), AppError> {
    if !installed
        .auth_security
        .ingest
        .check_ip_ingest_items(&scope.source_ip, item_count)
        .await
    {
        return Err(AppError::TooManyRequests);
    }
    let policy = ingest_abuse::policy_for_tier(scope.risk_tier);
    if !installed
        .auth_security
        .ingest
        .check_device_ingest_items(
            &scope.application_id,
            &scope.device_id,
            ingest_abuse::scaled_cost(item_count, policy.item_cost_multiplier),
        )
        .await
    {
        return Err(AppError::TooManyRequests);
    }
    Ok(())
}

async fn charge_device_token_budget(
    installed: &InstalledState,
    application_id: &str,
    device_id: &str,
    multiplier: u64,
) -> Result<bool, AppError> {
    Ok(ingest_bootstrap::charge_device_token(
        &installed.database,
        installed.auth_security.pepper(),
        application_id,
        device_id,
        multiplier,
    )
    .await?)
}

async fn charge_device_request_budget(
    installed: &InstalledState,
    application_id: &str,
    device_id: &str,
    multiplier: u64,
) -> bool {
    for _ in 0..std::cmp::max(multiplier, 1) {
        if !installed
            .auth_security
            .ingest
            .check_device_rate(application_id, device_id)
            .await
        {
            return false;
        }
    }
    true
}

fn ensure_batch_size(length: usize) -> Result<(), AppError> {
    if length > MAX_BATCH_ITEMS {
        return Err(AppError::Validation(format!(
            "maximum batch size is {MAX_BATCH_ITEMS}"
        )));
    }
    Ok(())
}

fn validate_with<T: ValidateTelemetry>(
    items: &mut [T],
    mut normalize: impl FnMut(&mut T) -> Result<(), &'static str>,
) -> (usize, Vec<RejectedItem>) {
    let mut accepted = 0;
    let mut rejected = Vec::new();
    for (index, item) in items.iter_mut().enumerate() {
        let result = normalize(item).and_then(|()| item.validate());
        if let Err(reason) = result {
            rejected.push(RejectedItem {
                index,
                reason: reason.to_string(),
            });
        } else {
            accepted += 1;
        }
    }
    (accepted, rejected)
}

fn normalize_live_event(
    scope: &IngestScope,
    item: &mut EventInput,
) -> Result<(), &'static str> {
    item.timestamp = None;
    item.session_id = None;
    bind_device_id(&scope.device_id, &mut item.anonymous_id)
}

fn normalize_live_error(
    scope: &IngestScope,
    item: &mut ErrorInput,
) -> Result<(), &'static str> {
    item.timestamp = None;
    item.session_id = None;
    bind_device_id(&scope.device_id, &mut item.anonymous_id)
}

fn bind_device_id(bound: &str, value: &mut Option<String>) -> Result<(), &'static str> {
    match value.as_deref() {
        Some(current) if current != bound => {
            Err("anonymous_id must match deviceId used to issue the ingest token")
        }
        Some(_) => Ok(()),
        None => {
            *value = Some(bound.to_owned());
            Ok(())
        }
    }
}

fn select_valid<T>(items: Vec<T>, rejected: &[RejectedItem]) -> Vec<T> {
    if rejected.is_empty() {
        return items;
    }
    let rejected_indices: std::collections::HashSet<_> =
        rejected.iter().map(|item| item.index).collect();
    items
        .into_iter()
        .enumerate()
        .filter_map(|(index, item)| {
            if rejected_indices.contains(&index) {
                None
            } else {
                Some(item)
            }
        })
        .collect()
}

fn validate_user_agent(value: &str) -> Result<&str, AppError> {
    let value = value.trim();
    if value.is_empty()
        || value.len() > 512
        || value.chars().any(|character| character.is_control())
    {
        return Err(AppError::Validation(
            "User-Agent must be 1..512 visible bytes".into(),
        ));
    }
    Ok(value)
}

fn validate_device_id(value: &str) -> Result<&str, AppError> {
    let value = value.trim();
    if value.len() < 4
        || value.len() > 128
        || !value.chars().all(|character| {
            character.is_ascii_alphanumeric() || matches!(character, '-' | '_' | '.' | ':')
        })
    {
        return Err(AppError::Validation(
            "deviceId must be 4..128 bytes using letters, digits, '-', '_', '.', or ':'".into(),
        ));
    }
    Ok(value)
}

pub(crate) fn anonymous_hash(value: &str, salt: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(value.as_bytes());
    hasher.update(salt.as_bytes());
    hex::encode(hasher.finalize())
}

#[cfg(test)]
mod tests {
    use super::{IngestScope, event_observation, normalize_live_event, simple_observation};
    use crate::{
        database::device_state::DeviceTelemetryKind,
        domain::telemetry::EventInput,
        services::ingest_abuse::RiskTier,
    };

    fn scope() -> IngestScope {
        IngestScope {
            application_id: "app".into(),
            environment_id: "env".into(),
            source_ip: "127.0.0.1".into(),
            device_id: "device-1234".into(),
            risk_tier: RiskTier::Low,
        }
    }

    fn event() -> EventInput {
        EventInput {
            name: "startup".into(),
            timestamp: Some(100),
            anonymous_id: None,
            session_id: Some("client-session".into()),
            app_version: Some("2.0.0".into()),
            launcher_version: Some("1.5.0".into()),
            os: Some("windows".into()),
            idempotency_key: None,
            attributes: Default::default(),
        }
    }

    #[test]
    fn signed_token_device_binding_blocks_identity_spoofing() {
        let scope = scope();
        let mut forged = event();
        forged.anonymous_id = Some("device-9999".into());
        assert!(normalize_live_event(&scope, &mut forged).is_err());
    }

    #[test]
    fn live_ingest_uses_token_identity_and_server_time_semantics() {
        let scope = scope();
        let mut event = event();
        assert!(normalize_live_event(&scope, &mut event).is_ok());
        assert_eq!(event.anonymous_id.as_deref(), Some("device-1234"));
        assert!(event.timestamp.is_none());
        assert!(event.session_id.is_none());
        assert_eq!(event.app_version.as_deref(), Some("2.0.0"));
        assert_eq!(event.launcher_version.as_deref(), Some("1.5.0"));
        assert_eq!(event.os.as_deref(), Some("windows"));
    }

    #[test]
    fn platform_selects_current_dimensions_at_server_receive_time() {
        let mut first = event();
        first.app_version = Some("1.0.0".into());
        let mut second = event();
        second.app_version = Some("2.0.0".into());
        second.os = Some("linux".into());
        let observation = event_observation(&[first, second]).unwrap();
        assert_eq!(
            observation.app_version.as_ref().map(|value| value.value.as_str()),
            Some("2.0.0")
        );
        assert_eq!(
            observation.os.as_ref().map(|value| value.value.as_str()),
            Some("linux")
        );
        assert_eq!(observation.telemetry_at, observation.received_at);
        assert!(observation.session_id.is_none());
    }

    #[test]
    fn metrics_and_logs_advance_server_owned_device_activity() {
        let observation = simple_observation(DeviceTelemetryKind::Metric, 2).unwrap();
        assert_eq!(observation.telemetry_at, observation.received_at);
        assert!(observation.session_id.is_none());
        assert!(observation.app_version.is_none());
    }
}
