use sha2::{Digest, Sha256};
use tracing::warn;

use crate::{
    database::{
        device_state_repo::{self, DeviceObservation, DeviceTelemetryKind, TimedDimension},
        ingest_auth_repo,
        telemetry_repo::TelemetryScope,
    },
    domain::telemetry::{
        BatchReceipt, ErrorInput, EventInput, LogInput, MAX_BATCH_ITEMS, MetricInput, RejectedItem,
        ValidateTelemetry,
    },
    error::AppError,
    ingest_signature,
    state::InstalledState,
};

#[derive(Clone, Copy, Debug)]
pub struct IngestTokenContext<'a> {
    pub client_ip: &'a str,
    pub user_agent: &'a str,
    pub raw_key: Option<&'a str>,
}

#[derive(Clone, Copy, Debug)]
pub struct IngestRequestContext<'a> {
    pub client_ip: &'a str,
    pub user_agent: &'a str,
    pub credential: Option<&'a str>,
    pub signature: Option<&'a str>,
    pub timestamp: Option<&'a str>,
    pub nonce: Option<&'a str>,
    pub method: &'a str,
    pub path: &'a str,
}

#[derive(Clone, Debug)]
pub struct IngestScope {
    pub application_id: String,
    pub environment_id: String,
    source_ip: Option<String>,
    device_id: Option<String>,
}

impl IngestScope {
    fn storage_scope(&self) -> TelemetryScope {
        TelemetryScope {
            application_id: self.application_id.clone(),
            environment_id: self.environment_id.clone(),
        }
    }

    pub(crate) fn signed_device_id(&self) -> Option<&str> {
        self.device_id.as_deref()
    }
}

#[derive(Debug, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct IngestTokenRequest {
    /// Stable pseudonymous/encrypted identifier generated by the client for the current device.
    /// Historical session/version/OS state is derived from telemetry by the platform.
    pub device_id: String,
}

#[derive(Debug, serde::Serialize)]
#[serde(rename_all = "camelCase")]
pub struct IngestTokenResponse {
    pub token: String,
    pub token_type: &'static str,
    pub expires_in: i64,
    pub expires_at: i64,
    pub signing_key: String,
    pub signature_version: &'static str,
    pub scopes: Vec<String>,
}

pub fn has_permission(scopes: &[String], required_perm: &str) -> bool {
    scopes.iter().any(|scope| {
        scope == "*"
            || scope == "ingest"
            || scope == "telemetry.ingest"
            || scope == required_perm
            || (required_perm == "telemetry.events"
                && (scope == "events" || scope == "ingest.events"))
            || (required_perm == "telemetry.metrics"
                && (scope == "metrics" || scope == "ingest.metrics"))
            || (required_perm == "telemetry.logs"
                && (scope == "logs" || scope == "ingest.logs"))
            || (required_perm == "telemetry.errors"
                && (scope == "errors" || scope == "ingest.errors"))
    })
}

pub fn match_user_agent(rule: &str, user_agent: &str) -> bool {
    let rule = rule.trim();
    if rule.is_empty() || rule == "*" {
        return true;
    }
    if user_agent.is_empty() {
        return false;
    }
    for part in rule.split(',') {
        let pattern = part.trim();
        if pattern.is_empty() {
            continue;
        }
        if let Some(prefix) = pattern.strip_suffix('*') {
            if user_agent.starts_with(prefix) {
                return true;
            }
        } else if user_agent == pattern || user_agent.contains(pattern) {
            return true;
        }
    }
    false
}

/// Exchange a long-lived bootstrap API key for a short-lived device-bound ingest token.
pub async fn issue_token(
    installed: &InstalledState,
    request: IngestTokenContext<'_>,
    body: IngestTokenRequest,
) -> Result<IngestTokenResponse, AppError> {
    let user_agent = validate_user_agent(request.user_agent)?;

    if !installed
        .auth_security
        .ingest
        .check_ip_token_rate(request.client_ip)
        .await
    {
        return Err(AppError::TooManyRequests);
    }

    let device_id = validate_device_id(&body.device_id)?.to_owned();
    let raw_key = request.raw_key.ok_or(AppError::Unauthorized)?;
    let hash = hex::encode(Sha256::digest(raw_key.as_bytes()));
    let context = ingest_auth_repo::api_key_context(
        &installed.database,
        &hash,
        chrono::Utc::now().timestamp_millis(),
    )
    .await?
    .ok_or(AppError::Unauthorized)?;

    if !installed
        .auth_security
        .ingest
        .check_device_enrollment(request.client_ip, &context.application_id, &device_id)
        .await
        || !installed
            .auth_security
            .ingest
            .check_device_token_rate(&context.application_id, &device_id)
            .await
    {
        return Err(AppError::TooManyRequests);
    }

    let client_binding = installed
        .auth_security
        .ingest
        .client_binding(user_agent, installed.auth_security.pepper());
    let (token, signing_key, expires_at) = installed.auth_security.ingest.issue_ingest_token(
        &context.application_id,
        &context.environment_id,
        &device_id,
        &client_binding,
        &context.scopes,
        120,
        installed.auth_security.pepper(),
    )?;

    Ok(IngestTokenResponse {
        token,
        token_type: "Bearer",
        expires_in: 120,
        expires_at,
        signing_key,
        signature_version: ingest_signature::SIGNATURE_VERSION,
        scopes: context.scopes,
    })
}

pub async fn scope_from_context_with_permission(
    installed: &InstalledState,
    request: IngestRequestContext<'_>,
    required_perm: &str,
    raw_body: &[u8],
) -> Result<IngestScope, AppError> {
    let user_agent = validate_user_agent(request.user_agent)?;

    if !installed
        .auth_security
        .ingest
        .check_ip_ingest_rate(request.client_ip)
        .await
        || !installed
            .auth_security
            .ingest
            .check_ip_ingest_bytes(request.client_ip, raw_body.len())
            .await
    {
        return Err(AppError::TooManyRequests);
    }

    let auth_header = request.credential.ok_or(AppError::Unauthorized)?;
    if auth_header.starts_with("sndt_") {
        signed_scope(installed, request, required_perm, raw_body, auth_header, user_agent).await
    } else {
        if !installed
            .auth_security
            .ingest
            .check_legacy_ingest_budget(request.client_ip, raw_body.len())
            .await
        {
            return Err(AppError::TooManyRequests);
        }
        let mut scope = scope_for_key_with_permission(installed, auth_header, required_perm).await?;
        scope.source_ip = Some(request.client_ip.to_owned());
        Ok(scope)
    }
}

async fn signed_scope(
    installed: &InstalledState,
    request: IngestRequestContext<'_>,
    required_perm: &str,
    raw_body: &[u8],
    token: &str,
    user_agent: &str,
) -> Result<IngestScope, AppError> {
    let claims = installed
        .auth_security
        .ingest
        .verify_ingest_token(token, installed.auth_security.pepper())
        .ok_or(AppError::Unauthorized)?;

    let expected_binding = installed
        .auth_security
        .ingest
        .client_binding(user_agent, installed.auth_security.pepper());
    if claims.client_binding != expected_binding || !has_permission(&claims.scopes, required_perm) {
        return Err(AppError::Forbidden);
    }

    let signature = request.signature.ok_or(AppError::Forbidden)?;
    let timestamp = request
        .timestamp
        .ok_or(AppError::Forbidden)?
        .parse::<i64>()
        .map_err(|_| AppError::Validation("invalid x-sonde-timestamp".into()))?;
    let nonce = request.nonce.ok_or(AppError::Forbidden)?;
    if nonce.len() < 8
        || nonce.len() > 128
        || nonce
            .chars()
            .any(|character| character.is_control() || character.is_whitespace())
    {
        return Err(AppError::Validation(
            "x-sonde-nonce must be 8..128 visible non-whitespace bytes".into(),
        ));
    }

    let signing_key = installed
        .auth_security
        .ingest
        .signing_key_for_claims(&claims, installed.auth_security.pepper());
    ingest_signature::verify(
        &signing_key,
        timestamp,
        nonce,
        request.method,
        request.path,
        raw_body,
        signature,
    )?;

    let now = chrono::Utc::now().timestamp_millis();
    if !installed
        .auth_security
        .ingest
        .check_and_record_nonce(&claims.token_id, nonce, now.saturating_add(120_000))
        .await
    {
        return Err(AppError::Forbidden);
    }

    if !installed
        .auth_security
        .ingest
        .check_device_rate(&claims.application_id, &claims.device_id)
        .await
        || !installed
            .auth_security
            .ingest
            .check_device_ingest_bytes(
                &claims.application_id,
                &claims.device_id,
                raw_body.len(),
            )
            .await
    {
        return Err(AppError::TooManyRequests);
    }

    Ok(IngestScope {
        application_id: claims.application_id,
        environment_id: claims.environment_id,
        source_ip: Some(request.client_ip.to_owned()),
        device_id: Some(claims.device_id),
    })
}

pub async fn scope_from_context(
    installed: &InstalledState,
    request: IngestRequestContext<'_>,
    raw_body: &[u8],
) -> Result<IngestScope, AppError> {
    scope_from_context_with_permission(installed, request, "telemetry.ingest", raw_body).await
}

pub async fn scope_for_key_with_permission(
    installed: &InstalledState,
    raw_key: &str,
    required_perm: &str,
) -> Result<IngestScope, AppError> {
    let hash = hex::encode(Sha256::digest(raw_key.as_bytes()));
    let context = ingest_auth_repo::api_key_context(
        &installed.database,
        &hash,
        chrono::Utc::now().timestamp_millis(),
    )
    .await?
    .ok_or(AppError::Unauthorized)?;

    if !has_permission(&context.scopes, required_perm) {
        return Err(AppError::Forbidden);
    }

    Ok(IngestScope {
        application_id: context.application_id,
        environment_id: context.environment_id,
        source_ip: None,
        device_id: None,
    })
}

pub async fn scope_for_key(
    installed: &InstalledState,
    raw_key: &str,
) -> Result<IngestScope, AppError> {
    scope_for_key_with_permission(installed, raw_key, "telemetry.ingest").await
}

pub async fn events(
    installed: &InstalledState,
    scope: &IngestScope,
    mut items: Vec<EventInput>,
) -> Result<BatchReceipt, AppError> {
    ensure_batch_size(items.len())?;
    charge_item_budget(installed, scope, items.len()).await?;
    let (accepted, rejected) = validate_with(&mut items, |item| bind_event_device(scope, item));
    let mut valid = select_valid(items, &rejected);
    let observation = event_observation(&valid);
    let key_salt = format!("{}:{}", scope.application_id, scope.environment_id);
    for item in &mut valid {
        item.anonymous_id = item
            .anonymous_id
            .take()
            .map(|id| anonymous_hash(&id, &key_salt));
    }
    let storage_scope = scope.storage_scope();
    installed
        .ingest_writer
        .write_events(&storage_scope, valid)
        .await?;
    observe_signed_device(installed, scope, &storage_scope, observation).await;
    Ok(BatchReceipt { accepted, rejected })
}

pub async fn metrics(
    installed: &InstalledState,
    scope: &IngestScope,
    mut items: Vec<MetricInput>,
) -> Result<BatchReceipt, AppError> {
    ensure_batch_size(items.len())?;
    charge_item_budget(installed, scope, items.len()).await?;
    let (accepted, rejected) = validate_with(&mut items, |_| Ok(()));
    let valid = select_valid(items, &rejected);
    let observation = simple_observation(
        DeviceTelemetryKind::Metric,
        valid.iter().map(|item| item.timestamp),
        valid.len(),
    );
    let storage_scope = scope.storage_scope();
    installed
        .ingest_writer
        .write_metrics(&storage_scope, valid)
        .await?;
    observe_signed_device(installed, scope, &storage_scope, observation).await;
    Ok(BatchReceipt { accepted, rejected })
}

pub async fn logs(
    installed: &InstalledState,
    scope: &IngestScope,
    mut items: Vec<LogInput>,
) -> Result<BatchReceipt, AppError> {
    ensure_batch_size(items.len())?;
    charge_item_budget(installed, scope, items.len()).await?;
    let (accepted, rejected) = validate_with(&mut items, |_| Ok(()));
    let valid = select_valid(items, &rejected);
    let observation = simple_observation(
        DeviceTelemetryKind::Log,
        valid.iter().map(|item| item.timestamp),
        valid.len(),
    );
    let storage_scope = scope.storage_scope();
    installed
        .ingest_writer
        .write_logs(&storage_scope, valid)
        .await?;
    observe_signed_device(installed, scope, &storage_scope, observation).await;
    Ok(BatchReceipt { accepted, rejected })
}

pub async fn errors(
    installed: &InstalledState,
    scope: &IngestScope,
    mut items: Vec<ErrorInput>,
) -> Result<BatchReceipt, AppError> {
    ensure_batch_size(items.len())?;
    charge_item_budget(installed, scope, items.len()).await?;
    let (accepted, rejected) = validate_with(&mut items, |item| bind_error_device(scope, item));
    let valid = select_valid(items, &rejected);
    let observation = error_observation(&valid);
    let storage_scope = scope.storage_scope();
    installed
        .ingest_writer
        .write_errors(&storage_scope, valid)
        .await?;
    observe_signed_device(installed, scope, &storage_scope, observation).await;
    Ok(BatchReceipt { accepted, rejected })
}

async fn observe_signed_device(
    installed: &InstalledState,
    scope: &IngestScope,
    storage_scope: &TelemetryScope,
    observation: Option<DeviceObservation>,
) {
    let (Some(device_id), Some(observation)) = (scope.signed_device_id(), observation) else {
        return;
    };
    let salt = format!("{}:{}", scope.application_id, scope.environment_id);
    let device_hash = anonymous_hash(device_id, &salt);
    if let Err(error) = device_state_repo::observe(
        &installed.database,
        storage_scope,
        &device_hash,
        &observation,
    )
    .await
    {
        warn!(
            error = %error,
            application_id = %scope.application_id,
            environment_id = %scope.environment_id,
            "failed to update derived device profile after telemetry ingest"
        );
    }
}

fn event_observation(items: &[EventInput]) -> Option<DeviceObservation> {
    if items.is_empty() {
        return None;
    }
    let received_at = chrono::Utc::now().timestamp_millis();
    let mut telemetry_at = i64::MIN;
    let mut session_id = None;
    let mut app_version = None;
    let mut launcher_version = None;
    let mut os = None;
    for item in items {
        let timestamp = item.timestamp.unwrap_or(received_at);
        telemetry_at = telemetry_at.max(timestamp);
        update_timed_dimension(&mut session_id, item.session_id.as_deref(), timestamp);
        update_timed_dimension(&mut app_version, item.app_version.as_deref(), timestamp);
        update_timed_dimension(
            &mut launcher_version,
            item.launcher_version.as_deref(),
            timestamp,
        );
        update_timed_dimension(&mut os, item.os.as_deref(), timestamp);
    }
    Some(DeviceObservation {
        kind: DeviceTelemetryKind::Event,
        received_at,
        telemetry_at,
        item_count: items.len(),
        session_id,
        app_version,
        launcher_version,
        os,
    })
}

fn error_observation(items: &[ErrorInput]) -> Option<DeviceObservation> {
    if items.is_empty() {
        return None;
    }
    let received_at = chrono::Utc::now().timestamp_millis();
    let mut telemetry_at = i64::MIN;
    let mut session_id = None;
    let mut app_version = None;
    let mut launcher_version = None;
    let mut os = None;
    for item in items {
        let timestamp = item.timestamp.unwrap_or(received_at);
        telemetry_at = telemetry_at.max(timestamp);
        update_timed_dimension(&mut session_id, item.session_id.as_deref(), timestamp);
        update_timed_dimension(&mut app_version, item.app_version.as_deref(), timestamp);
        update_timed_dimension(
            &mut launcher_version,
            item.launcher_version.as_deref(),
            timestamp,
        );
        update_timed_dimension(&mut os, item.os.as_deref(), timestamp);
    }
    Some(DeviceObservation {
        kind: DeviceTelemetryKind::Error,
        received_at,
        telemetry_at,
        item_count: items.len(),
        session_id,
        app_version,
        launcher_version,
        os,
    })
}

fn simple_observation(
    kind: DeviceTelemetryKind,
    timestamps: impl Iterator<Item = Option<i64>>,
    item_count: usize,
) -> Option<DeviceObservation> {
    if item_count == 0 {
        return None;
    }
    let received_at = chrono::Utc::now().timestamp_millis();
    let telemetry_at = timestamps
        .map(|timestamp| timestamp.unwrap_or(received_at))
        .max()
        .unwrap_or(received_at);
    Some(DeviceObservation {
        kind,
        received_at,
        telemetry_at,
        item_count,
        session_id: None,
        app_version: None,
        launcher_version: None,
        os: None,
    })
}

fn update_timed_dimension(target: &mut Option<TimedDimension>, value: Option<&str>, timestamp: i64) {
    let Some(value) = value else {
        return;
    };
    if target
        .as_ref()
        .is_none_or(|current| timestamp >= current.timestamp)
    {
        *target = Some(TimedDimension {
            value: value.to_owned(),
            timestamp,
        });
    }
}

async fn charge_item_budget(
    installed: &InstalledState,
    scope: &IngestScope,
    item_count: usize,
) -> Result<(), AppError> {
    let Some(source_ip) = scope.source_ip.as_deref() else {
        return Ok(());
    };
    if !installed
        .auth_security
        .ingest
        .check_ip_ingest_items(source_ip, item_count)
        .await
    {
        return Err(AppError::TooManyRequests);
    }
    if let Some(device_id) = scope.device_id.as_deref() {
        if !installed
            .auth_security
            .ingest
            .check_device_ingest_items(&scope.application_id, device_id, item_count)
            .await
        {
            return Err(AppError::TooManyRequests);
        }
    } else if !installed
        .auth_security
        .ingest
        .check_legacy_ingest_items(source_ip, item_count)
        .await
    {
        return Err(AppError::TooManyRequests);
    }
    Ok(())
}

fn ensure_batch_size(length: usize) -> Result<(), AppError> {
    if length > MAX_BATCH_ITEMS {
        return Err(AppError::Validation(format!(
            "maximum batch size is {MAX_BATCH_ITEMS}"
        )));
    }
    Ok(())
}

fn validate_with<T: ValidateTelemetry>(
    items: &mut [T],
    mut bind: impl FnMut(&mut T) -> Result<(), &'static str>,
) -> (usize, Vec<RejectedItem>) {
    let mut accepted = 0;
    let mut rejected = Vec::new();
    for (index, item) in items.iter_mut().enumerate() {
        let result = bind(item).and_then(|()| item.validate());
        if let Err(reason) = result {
            rejected.push(RejectedItem {
                index,
                reason: reason.to_string(),
            });
        } else {
            accepted += 1;
        }
    }
    (accepted, rejected)
}

fn bind_event_device(scope: &IngestScope, item: &mut EventInput) -> Result<(), &'static str> {
    bind_device_id(scope.device_id.as_deref(), &mut item.anonymous_id)
}

fn bind_error_device(scope: &IngestScope, item: &mut ErrorInput) -> Result<(), &'static str> {
    bind_device_id(scope.device_id.as_deref(), &mut item.anonymous_id)
}

fn bind_device_id(bound: Option<&str>, value: &mut Option<String>) -> Result<(), &'static str> {
    let Some(bound) = bound else {
        return Ok(());
    };
    match value.as_deref() {
        Some(current) if current != bound => {
            Err("anonymous_id must match deviceId used to issue the ingest token")
        }
        Some(_) => Ok(()),
        None => {
            *value = Some(bound.to_owned());
            Ok(())
        }
    }
}

fn select_valid<T>(items: Vec<T>, rejected: &[RejectedItem]) -> Vec<T> {
    if rejected.is_empty() {
        return items;
    }
    let rejected_indices: std::collections::HashSet<_> =
        rejected.iter().map(|item| item.index).collect();
    items
        .into_iter()
        .enumerate()
        .filter_map(|(index, item)| {
            if rejected_indices.contains(&index) {
                None
            } else {
                Some(item)
            }
        })
        .collect()
}

fn validate_user_agent(value: &str) -> Result<&str, AppError> {
    let value = value.trim();
    if value.is_empty()
        || value.len() > 512
        || value.chars().any(|character| character.is_control())
    {
        return Err(AppError::Validation(
            "User-Agent must be 1..512 visible bytes".into(),
        ));
    }
    Ok(value)
}

fn validate_device_id(value: &str) -> Result<&str, AppError> {
    let value = value.trim();
    if value.len() < 4
        || value.len() > 128
        || !value.chars().all(|character| {
            character.is_ascii_alphanumeric() || matches!(character, '-' | '_' | '.' | ':')
        })
    {
        return Err(AppError::Validation(
            "deviceId must be 4..128 bytes using letters, digits, '-', '_', '.', or ':'".into(),
        ));
    }
    Ok(value)
}

pub(crate) fn anonymous_hash(value: &str, salt: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(value.as_bytes());
    hasher.update(salt.as_bytes());
    hex::encode(hasher.finalize())
}

#[cfg(test)]
mod tests {
    use super::{IngestScope, bind_event_device, event_observation, simple_observation};
    use crate::{
        database::device_state_repo::DeviceTelemetryKind,
        domain::telemetry::EventInput,
    };

    fn scope() -> IngestScope {
        IngestScope {
            application_id: "app".into(),
            environment_id: "env".into(),
            source_ip: Some("127.0.0.1".into()),
            device_id: Some("device-1234".into()),
        }
    }

    fn event() -> EventInput {
        EventInput {
            name: "startup".into(),
            timestamp: Some(100),
            anonymous_id: None,
            session_id: Some("session-current".into()),
            app_version: Some("2.0.0".into()),
            launcher_version: Some("1.5.0".into()),
            os: Some("windows".into()),
            idempotency_key: None,
            attributes: Default::default(),
        }
    }

    #[test]
    fn signed_token_device_binding_blocks_identity_spoofing() {
        let scope = scope();
        let mut forged = event();
        forged.anonymous_id = Some("device-9999".into());
        assert!(bind_event_device(&scope, &mut forged).is_err());
    }

    #[test]
    fn signed_token_injects_only_device_identity() {
        let scope = scope();
        let mut event = event();
        assert!(bind_event_device(&scope, &mut event).is_ok());
        assert_eq!(event.anonymous_id.as_deref(), Some("device-1234"));
        assert_eq!(event.session_id.as_deref(), Some("session-current"));
        assert_eq!(event.app_version.as_deref(), Some("2.0.0"));
        assert_eq!(event.launcher_version.as_deref(), Some("1.5.0"));
        assert_eq!(event.os.as_deref(), Some("windows"));
    }

    #[test]
    fn platform_selects_latest_current_dimensions_from_telemetry() {
        let mut older = event();
        older.timestamp = Some(100);
        older.app_version = Some("1.0.0".into());
        let mut newer = event();
        newer.timestamp = Some(200);
        newer.app_version = Some("2.0.0".into());
        newer.os = Some("linux".into());
        let observation = event_observation(&[older, newer]).unwrap();
        assert_eq!(
            observation.app_version.as_ref().map(|value| value.value.as_str()),
            Some("2.0.0")
        );
        assert_eq!(
            observation.os.as_ref().map(|value| value.value.as_str()),
            Some("linux")
        );
        assert_eq!(observation.telemetry_at, 200);
    }

    #[test]
    fn metrics_and_logs_can_advance_device_activity_without_dimensions() {
        let observation = simple_observation(
            DeviceTelemetryKind::Metric,
            [Some(100), Some(200)].into_iter(),
            2,
        )
        .unwrap();
        assert_eq!(observation.telemetry_at, 200);
        assert!(observation.session_id.is_none());
        assert!(observation.app_version.is_none());
    }
}
