use sea_orm_migration::prelude::*;

use super::columns::{
    bigint, boolean, create_index, create_table, double, integer, nullable_bigint, nullable_double,
    nullable_string, nullable_text, string, text,
};

pub(super) async fn create_identity_tables(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    create_table(
        manager,
        "system_state",
        vec![string("key").primary_key().to_owned(), text("value")],
    )
    .await?;
    create_table(
        manager,
        "users",
        vec![
            string("id").primary_key().to_owned(),
            string("email").unique_key().to_owned(),
            string("username"),
            text("password_hash"),
            string("locale"),
            boolean("active"),
            bigint("created_at"),
        ],
    )
    .await?;
    create_table(
        manager,
        "roles",
        vec![
            string("id").primary_key().to_owned(),
            string("name").unique_key().to_owned(),
            boolean("builtin"),
            text("permissions"),
            bigint("created_at"),
        ],
    )
    .await?;
    create_table(
        manager,
        "sessions",
        vec![
            string("id").primary_key().to_owned(),
            string("user_id"),
            string("token_hash").unique_key().to_owned(),
            string("csrf_token"),
            bigint("expires_at"),
            bigint("created_at"),
        ],
    )
    .await?;
    create_table(
        manager,
        "role_bindings",
        vec![
            string("id").primary_key().to_owned(),
            string("user_id"),
            string("role_id"),
            nullable_string("application_id"),
            bigint("created_at"),
        ],
    )
    .await
}

pub(super) async fn create_application_tables(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    create_table(
        manager,
        "applications",
        vec![
            string("id").primary_key().to_owned(),
            string("name"),
            string("slug").unique_key().to_owned(),
            integer("retention_days"),
            nullable_string("owner_user_id"),
            boolean("is_public"),
            nullable_text("description"),
            nullable_string("github_url"),
            nullable_string("website_url"),
            nullable_text("custom_header"),
            bigint("created_at"),
        ],
    )
    .await?;
    create_table(
        manager,
        "environments",
        vec![
            string("id").primary_key().to_owned(),
            string("application_id"),
            string("name"),
            string("slug"),
            bigint("created_at"),
        ],
    )
    .await?;
    create_table(
        manager,
        "api_keys",
        vec![
            string("id").primary_key().to_owned(),
            string("application_id"),
            string("environment_id"),
            string("name"),
            string("key_hash").unique_key().to_owned(),
            string("key_prefix"),
            text("scopes"),
            nullable_bigint("expires_at"),
            nullable_bigint("last_used_at"),
            nullable_bigint("revoked_at"),
            bigint("created_at"),
        ],
    )
    .await
}

pub(super) async fn create_telemetry_tables(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    create_table(
        manager,
        "events",
        vec![
            string("id").primary_key().to_owned(),
            string("application_id"),
            string("environment_id"),
            string("name"),
            bigint("timestamp"),
            string("day"),
            nullable_string("anonymous_id"),
            nullable_string("session_id"),
            nullable_string("app_version"),
            nullable_string("launcher_version"),
            nullable_string("os"),
            text("attributes"),
            nullable_string("dedupe_key"),
            bigint("received_at"),
        ],
    )
    .await?;
    create_table(
        manager,
        "metric_points",
        vec![
            string("id").primary_key().to_owned(),
            string("application_id"),
            string("environment_id"),
            string("name"),
            string("metric_type"),
            double("value"),
            nullable_string("unit"),
            bigint("timestamp"),
            text("attributes"),
            bigint("received_at"),
        ],
    )
    .await?;
    create_table(
        manager,
        "logs",
        vec![
            string("id").primary_key().to_owned(),
            string("application_id"),
            string("environment_id"),
            string("level"),
            text("message"),
            nullable_string("logger"),
            nullable_string("trace_id"),
            nullable_string("span_id"),
            bigint("timestamp"),
            text("attributes"),
            bigint("received_at"),
        ],
    )
    .await?;
    create_table(
        manager,
        "daily_aggregates",
        vec![
            string("id").primary_key().to_owned(),
            string("application_id"),
            string("environment_id"),
            string("day"),
            string("kind"),
            string("dimension"),
            string("dimension_value"),
            bigint("count"),
            nullable_double("sum"),
            bigint("updated_at"),
        ],
    )
    .await?;
    create_index(
        manager,
        "idx_events_scope_time",
        "events",
        &["application_id", "environment_id", "timestamp"],
        false,
    )
    .await?;
    create_index(
        manager,
        "idx_events_day_user",
        "events",
        &["application_id", "day", "anonymous_id"],
        false,
    )
    .await?;
    create_index(manager, "uq_events_dedupe", "events", &["dedupe_key"], true).await?;
    create_index(
        manager,
        "idx_metrics_scope_time",
        "metric_points",
        &["application_id", "environment_id", "timestamp"],
        false,
    )
    .await?;
    create_index(
        manager,
        "idx_logs_scope_time",
        "logs",
        &["application_id", "environment_id", "timestamp"],
        false,
    )
    .await
}

pub(super) async fn create_operations_tables(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    create_table(
        manager,
        "import_runs",
        vec![
            string("id").primary_key().to_owned(),
            string("source_type"),
            string("source_hash").unique_key().to_owned(),
            string("application_id"),
            string("environment_id"),
            string("status"),
            bigint("inserted"),
            bigint("deduped"),
            bigint("rejected"),
            bigint("created_at"),
        ],
    )
    .await?;
    create_table(
        manager,
        "alert_rules",
        vec![
            string("id").primary_key().to_owned(),
            string("application_id"),
            string("name"),
            boolean("enabled"),
            string("source_kind"),
            text("query_json"),
            integer("window_minutes"),
            integer("cooldown_seconds"),
            string("last_state"),
            nullable_bigint("last_evaluated_at"),
            bigint("created_at"),
        ],
    )
    .await?;
    create_table(
        manager,
        "notification_channels",
        vec![
            string("id").primary_key().to_owned(),
            string("name"),
            string("kind"),
            text("config_json"),
            boolean("enabled"),
            bigint("created_at"),
        ],
    )
    .await?;
    create_table(
        manager,
        "alert_deliveries",
        vec![
            string("id").primary_key().to_owned(),
            string("rule_id"),
            string("channel_id"),
            string("status"),
            integer("attempts"),
            nullable_text("last_error"),
            nullable_bigint("next_attempt_at"),
            bigint("created_at"),
        ],
    )
    .await?;
    create_table(
        manager,
        "audit_log",
        vec![
            string("id").primary_key().to_owned(),
            nullable_string("actor_user_id"),
            string("action"),
            string("resource_type"),
            nullable_string("resource_id"),
            text("metadata"),
            bigint("created_at"),
        ],
    )
    .await
}
